apiVersion: v1
kind: Service
metadata:
  name: {{ include "securesend.fullname" . }}
  labels:
    {{- include "securesend.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "securesend.selectorLabels" . | nindent 4 }}
{{- if .Values.management.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "securesend.fullname" . }}-management
  labels:
    {{- include "securesend.labels" . | nindent 4 }}
    app.kubernetes.io/component: management
  {{- with .Values.management.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: management
      port: {{ .Values.management.port }}
      targetPort: management
      protocol: TCP
  selector:
    {{- include "securesend.selectorLabels" . | nindent 4 }}
{{- end }}
